const CONFIG = {
  TYPOGRAPHY_COLOR_PRIMARY: '#2e405b',
  TYPOGRAPHY_COLOR_TITLE: '#276077',

  // 博客標題 雙語言
  TYPOGRAPHY_BLOG_NAME: process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME || '闲云野鹤',
  TYPOGRAPHY_BLOG_NAME_EN: process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME_EN || process.env.NEXT_PUBLIC_TYPOGRAPHY_BLOG_NAME || 'A Free Spirit',

  TYPOGRAPHY_POST_AD_ENABLE: process.env.NEXT_PUBLIC_TYPOGRAPHY_POST_AD_ENABLE || false, // 文章列表是否插入广告

  TYPOGRAPHY_POST_COVER_ENABLE: process.env.NEXT_PUBLIC_TYPOGRAPHY_POST_COVER_ENABLE || false, // 是否展示博客封面

  TYPOGRAPHY_ARTICLE_RECOMMEND_POSTS: process.env.NEXT_PUBLIC_TYPOGRAPHY_ARTICLE_RECOMMEND_POSTS || true, // 文章详情底部显示推荐

  TYPOGRAPHY_POST_LIST_PREVIEW: true, // 显示文章预览
  TYPOGRAPHY_POST_LIST_SUMMARY: true, // 显示用户自定义摘要，有预览时优先只展示预览
  
  // 菜单配置
  TYPOGRAPHY_MENU_CATEGORY: false, // 显示分类
  TYPOGRAPHY_MENU_TAG: false, // 显示标签
  TYPOGRAPHY_MENU_ARCHIVE: false, // 显示归档

  TYPOGRAPHY_RIGHT_BAR: true, // 是否显示右侧栏
  TYPOGRAPHY_RIGHT_LATEST_POSTS: true, // 右侧栏最新文章
  TYPOGRAPHY_RIGHT_CATEGORY_LIST: true, // 右侧边栏文章分类列表
  TYPOGRAPHY_RIGHT_TAG_LIST: true, // 右侧边栏标签分类列表
  
}
export default CONFIG
